### ISSUE TITLE
Track how fast each proxy responds and prefer the faster proxies.

### ISSUE THREAD

**Issue by svetlyak40wt** [darthbear/scrapy-proxynova#5]
We could track last 10 response times in deque for each proxy. And from time to time resort them according to the average response time.

Selection should use gaussian distrubution, like that:

``` python
from random import gauss

proxies = [some list where fastest proxies go first]

index = int(round(gauss(0, len(proxies) / 3.0)))
index = min(index, len(proxies) - 1)

return proxies[index]
```

**Comment by darthbear** [comment]
Good idea. I was thinking at first of something to simply exclude proxies which have failed or timed out a certain number of times but I like your approach better! In your case the failed proxies will go at the end of the list which is better than excluding them since there might have been slow because a temporary outage.

**Comment by svetlyak40wt** [comment]
Seems, nobody interested in such improvement.

Closing this old issue. Thanks to https://12forks.com MVP for pointing to it.
